# Render Blueprint for Freelance Market
# Reference: https://render.com/docs/blueprint-spec

services:
  - type: web
    name: freelance-market
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn freelance_market.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DJANGO_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: your-render-app-url.onrender.com
      - key: DEBUG
        value: false
      - key: DISABLE_COLLECTSTATIC
        value: 1
      - key: DB_ENGINE
        value: mysql
      - key: DB_NAME
        value: freelance_market
      - key: DB_USER
        value: freelance_user
      - key: DB_PASSWORD
        generateValue: true
      - key: DB_HOST
        value: ${MYSQLHOST}
      - key: DB_PORT
        value: ${MYSQLPORT}
    plan: free
    autoDeploy: true

  # MySQL database
  - type: mysql
    name: freelance-market-db
    plan: free
    databaseName: freelance_market
    user: freelance_user
    ipAllowList: []
    # Uncomment the following line to enable external connections
    # allowAllExternalConnections: true

# Create a Redis instance if needed (uncomment if your app uses Redis)
#  - type: redis
#    name: freelance-market-redis
#    plan: free
#    ipAllowList: []
