# Generated by Django 5.2.1 on 2025-06-15 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_alter_proposalattachment_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who triggered this notification",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actor_job_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                help_text="The user who will receive this notification",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
