# Generated by Django 5.2.1 on 2025-06-18 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_order_orderdelivery"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="escrow_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="last_revision_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="max_revisions",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="order",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Payment Pending"),
                    ("held_in_escrow", "Held in Escrow"),
                    ("released", "Payment Released"),
                    ("refunded", "Payment Refunded"),
                    ("disputed", "Payment Disputed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="requirements",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="order",
            name="revision_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("in_progress", "In Progress"),
                    ("delivered", "Delivered"),
                    ("approved", "Approved"),
                    ("revision_requested", "Revision Requested"),
                    ("cancelled", "Cancelled"),
                    ("disputed", "In Dispute"),
                ],
                default="initiated",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="jobs_order_status_833585_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["payment_status"], name="jobs_order_payment_433286_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["client"], name="jobs_order_client__af750c_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["freelancer"], name="jobs_order_freelan_0bba69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["deadline"], name="jobs_order_deadlin_62b008_idx"
            ),
        ),
    ]
