# Generated by Django 5.2.3 on 2025-06-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_order_amount_order_completed_at_order_deadline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("in_progress", "In Progress"),
                    ("delivered", "Delivered"),
                    ("approved", "Approved"),
                    ("completed", "Completed"),
                    ("revision_requested", "Revision Requested"),
                    ("cancelled", "Cancelled"),
                    ("disputed", "In Dispute"),
                ],
                default="initiated",
                max_length=30,
            ),
        ),
    ]
