# Generated by Django 5.2.3 on 2025-06-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="escrow_reference",
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Payment Pending"),
                    ("paid", "Paid"),
                    ("refunded", "Payment Refunded"),
                    ("disputed", "Payment Disputed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
