# Generated by Django 5.2.3 on 2025-06-22 09:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_remove_order_escrow_reference_and_more"),
        ("reviews", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewHelpfulVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_helpful",
                    models.BooleanField(default=True, verbose_name="is helpful"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "helpful vote",
                "verbose_name_plural": "helpful votes",
            },
        ),
        migrations.AddField(
            model_name="review",
            name="communication_rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "1 - Poor"),
                    (2, "2 - Fair"),
                    (3, "3 - Average"),
                    (4, "4 - Good"),
                    (5, "5 - Excellent"),
                ],
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="communication",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="deadline_rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "1 - Poor"),
                    (2, "2 - Fair"),
                    (3, "3 - Average"),
                    (4, "4 - Good"),
                    (5, "5 - Excellent"),
                ],
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="meeting deadlines",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="helpful_count",
            field=models.PositiveIntegerField(default=0, verbose_name="helpful count"),
        ),
        migrations.AddField(
            model_name="review",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Mark if the review has been verified by admin",
                verbose_name="is verified",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="professionalism_rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "1 - Poor"),
                    (2, "2 - Fair"),
                    (3, "3 - Average"),
                    (4, "4 - Good"),
                    (5, "5 - Excellent"),
                ],
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="professionalism",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="quality_rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "1 - Poor"),
                    (2, "2 - Fair"),
                    (3, "3 - Average"),
                    (4, "4 - Good"),
                    (5, "5 - Excellent"),
                ],
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="quality of work",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="response",
            field=models.TextField(blank=True, null=True, verbose_name="response"),
        ),
        migrations.AddField(
            model_name="review",
            name="response_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="response date"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AddField(
            model_name="review",
            name="was_edited",
            field=models.BooleanField(default=False, verbose_name="was edited"),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="review",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="jobs.order",
                verbose_name="order",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 - Poor"),
                    (2, "2 - Fair"),
                    (3, "3 - Average"),
                    (4, "4 - Good"),
                    (5, "5 - Excellent"),
                ],
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="overall rating",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews_given",
                to=settings.AUTH_USER_MODEL,
                verbose_name="reviewer",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user_being_reviewed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews_received",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user being reviewed",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["user_being_reviewed", "is_verified"],
                name="reviews_rev_user_be_4da444_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["rating"], name="reviews_rev_rating_2db6dd_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["created_at"], name="reviews_rev_created_bdcc91_idx"
            ),
        ),
        migrations.AddField(
            model_name="reviewhelpfulvote",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="helpful_votes",
                to="reviews.review",
                verbose_name="review",
            ),
        ),
        migrations.AddField(
            model_name="reviewhelpfulvote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="helpful_votes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reviewhelpfulvote",
            unique_together={("review", "user")},
        ),
    ]
