# Generated by Django 5.2.3 on 2025-06-19 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_add_default_payment_methods"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={
                "ordering": ["-is_primary", "-created_at"],
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
            },
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="account_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="account_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="branch_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="iban",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="swift_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_methods",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="name",
            field=models.CharField(
                choices=[
                    ("azampesa", "AzamPesa"),
                    ("mtn", "MTN Mobile Money"),
                    ("tigopesa", "Tigo Pesa"),
                    ("halopesa", "HaloPesa"),
                    ("bank", "Bank Transfer"),
                ],
                default="azampesa",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paymentmethod",
            unique_together={("user", "name", "account_number")},
        ),
    ]
