# Generated by Django 5.2.3 on 2025-06-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_paymentmethod_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="name",
            field=models.CharField(
                choices=[
                    ("azampesa", "AzamPesa"),
                    ("mpesa", "MPESA"),
                    ("tigopesa", "Tigo Pesa"),
                    ("halopesa", "HaloPesa"),
                    ("bank", "Bank Transfer"),
                ],
                default="azampesa",
                max_length=20,
            ),
        ),
    ]
