# Generated by Django 5.2.1 on 2025-06-12 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messagesys", "0001_initial"),
    ]

    operations = []
