# Generated by Django 5.2.1 on 2025-06-13 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messagesys", "0002_initial_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thread",
            name="initiator",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="job",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="participants",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="recipient",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="Thread",
        ),
    ]
