# Generated by Django 5.2.3 on 2025-06-20 08:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_alter_order_status"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderreview",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "order review",
                "verbose_name_plural": "order reviews",
            },
        ),
        migrations.AddField(
            model_name="orderreview",
            name="is_client_review",
            field=models.BooleanField(
                default=False,
                help_text="True if this is a client reviewing a freelancer",
                verbose_name="is client review",
            ),
        ),
        migrations.AddField(
            model_name="orderreview",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="orderreview",
            name="client",
            field=models.ForeignKey(
                db_column="client_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="client",
            ),
        ),
        migrations.AlterField(
            model_name="orderreview",
            name="comment",
            field=models.TextField(blank=True, verbose_name="comment"),
        ),
        migrations.AlterField(
            model_name="orderreview",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="orderreview",
            name="freelancer",
            field=models.ForeignKey(
                db_column="freelancer_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="freelancer_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="freelancer",
            ),
        ),
        migrations.AlterField(
            model_name="orderreview",
            name="order",
            field=models.OneToOneField(
                db_column="order_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="jobs.order",
                verbose_name="order",
            ),
        ),
        migrations.AlterField(
            model_name="orderreview",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 - Poor"),
                    (2, "2 - Fair"),
                    (3, "3 - Average"),
                    (4, "4 - Good"),
                    (5, "5 - Excellent"),
                ],
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="rating",
            ),
        ),
    ]
